version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: health_clinic_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d health_clinic_db']
      interval: 5s
      timeout: 5s
      retries: 5

  graphql-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://admin:password123@db:5432/health_clinic_db
      NODE_ENV: development
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
